groups:
  - name: Alerts
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:{% raw %}
          summary: "Instance Down - [{{ $labels.instance }}]"
          description: "Instance Down - [{{ $labels.instance }}]"{% endraw %}

{% for component in components %}
      - alert: ServiceDown - {{item}} Component
        expr: node_systemd_unit_state{exported_name="{{component}}.service",state="active"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:{% raw %}
          summary: "Service Down - [{{ $labels.exported_name }}]"
          description: "Service Down - [{{ $labels.exported_name }}]"{% endraw %}

{% endfor %}
